---
# roles/webserver/tasks/main.yml

- name: Entferne defekte php7.4.load-Symlink
  ansible.builtin.file:
    path: /etc/apache2/mods-enabled/php7.4.load
    state: absent

- name: Entferne defekte php7.4.conf-Symlink
  ansible.builtin.file:
    path: /etc/apache2/mods-enabled/php7.4.conf
    state: absent

- name: Entferne defekte php8.1.load-Symlink
  ansible.builtin.file:
    path: /etc/apache2/mods-enabled/php8.1.load
    state: absent

- name: Entferne defekte php8.1.conf-Symlink
  ansible.builtin.file:
    path: /etc/apache2/mods-enabled/php8.1.conf
    state: absent

- name: Aktiviere Apache-PHP8.2-Modul
  community.general.apache2_module:
    name: php8.2
    state: present
  notify: Reload Apache

- name: Setze PHP max_input_vars für Moodle
  ansible.builtin.ini_file:
    path: /etc/php/8.2/apache2/conf.d/99-moodle.ini
    section: PHP
    option: max_input_vars
    value: '5000'
    owner: root
    group: root
    mode: '0644'
  notify: Reload Apache

- name: Installiere Redis-Server und PHP-Extension
  ansible.builtin.apt:
    name:
      - redis-server
      - php8.2-redis
    state: present
    update_cache: true

- name: Aktiviere PHP-Redis-Extension
  ansible.builtin.command:
    cmd: phpenmod redis
    creates: /etc/php/8.2/mods-enabled/redis.ini
  notify: Reload Apache
  become: true

- name: Stelle sicher, dass Redis läuft
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true

- name: Installiere Apache2
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true

- name: Aktiviere benötigte Apache-Module
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - headers
    - expires
    - ssl
  notify: Reload Apache

- name: Erstelle DocumentRoot für Moodle
  ansible.builtin.file:
    path: "{{ moodle_www_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Deploy Moodle VirtualHost-Konfiguration
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/moodle.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload Apache

- name: Aktiviere Moodle-Site
  ansible.builtin.command:
    cmd: a2ensite moodle.conf
  args:
    creates: /etc/apache2/sites-enabled/moodle.conf
  notify: Reload Apache

- name: Deaktiviere default Site
  ansible.builtin.command:
    cmd: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: Reload Apache

- name: Stelle sicher, dass Apache2 läuft
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
