- name: Provisioniere Moodle-Server (DB, Webserver & Moodle)
  hosts: moodle_servers
  become: true

  roles:
    - role: iptables
      tags:
        - iptables
    - role: postgres
      tags:
        - postgres
    - role: apache
      tags:
        - apache
    - role: moodle
      tags:
        - moodle
