- name: Provisioniere Moodle-Server (DB, Webserver & Moodle)
  hosts: moodle_servers
  become: true
  pre_tasks:
    - name: Importiere iptables Pre-Tasks
      ansible.builtin.import_tasks: playbooks/pre_tasks/iptables.yml
      tags:
        - iptables
  roles:
    - role: iptables
      tags:
        - iptables
    - role: postgres
      tags:
        - postgres
    - role: apache
      tags:
        - apache
    - role: moodle
      tags:
        - moodle
