---
- name: Setze Standard-Policies für iptables
  ansible.builtin.iptables:
    table: filter
    chain: "{{ item.chain }}"
    policy: "{{ item.policy }}"
  loop: "{{ iptables_default_policy }}"
  tags: iptables
  notify: Save iptables

- name: Erlaube definierte Ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: "{{ item.proto }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
  loop: "{{ iptables_allowed_ports }}"
  tags: iptables
  notify: Save iptables

- name: Erlaube alle ausgehenden Verbindungen
  ansible.builtin.iptables:
    chain: OUTPUT
    jump: ACCEPT
  tags: iptables
  notify: Save iptables

- name: Pre-Task Erlaube SSH und bereits etablierte Verbindungen
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: "RELATED,ESTABLISHED"
    jump: ACCEPT
  tags: iptables
  notify: Save iptables

- name: Erlaube SSH
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT
  tags: iptables
  notify: Save iptables
