---
# roles/moodle/tasks/main.yml

# 1) PHP 8.1 PPA hinzufügen (für Ubuntu-Versionen ohne PHP8.1 im Main-Repo)
- name: Füge Ondřej Surý PHP PPA hinzu
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Aktualisiere apt-Cache
  ansible.builtin.apt:
    update_cache: true

- name: Installiere PHP 8.2 und Extensions für Moodle
  ansible.builtin.apt:
    name:
      - php8.2
      - php8.2-cli
      - libapache2-mod-php8.2
      - php8.2-gd
      - php8.2-curl
      - php8.2-xml
      - php8.2-mbstring
      - php8.2-zip
      - php8.2-intl
      - php8.2-pgsql
    state: present
    update_cache: true

- name: Erstelle Moodle Web-Verzeichnis
  ansible.builtin.file:
    path: "{{ moodle_www_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Installiere Git
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true

- name: Mark Moodle webroot as safe Git directory
  community.general.git_config:
    name: safe.directory
    scope: global
    value: "{{ moodle_www_root }}"

- name: Klone Moodle Repository
  ansible.builtin.git:
    repo: https://github.com/moodle/moodle.git
    dest: "{{ moodle_www_root }}"
    version: "MOODLE_500_STABLE"
    update: true
    force: true

- name: Erstelle moodledata-Verzeichnis
  ansible.builtin.file:
    path: "{{ moodle_data_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0770'

- name: Setze Berechtigungen für Moodle Web-Verzeichnis
  ansible.builtin.file:
    path: "{{ moodle_www_root }}"
    recurse: true
    owner: www-data
    group: www-data
    mode: '0755'

- name: Deploy Moodle config.php
  ansible.builtin.template:
    src: config.php.j2
    dest: "{{ moodle_www_root }}/config.php"
    owner: www-data
    group: www-data
    mode: '0644'

# Deaktiviere altes PHP-Modul und aktiviere PHP 8.2 im Apache
- name: Entferne defekte php8.1.load-Symlink
  ansible.builtin.file:
    path: /etc/apache2/mods-enabled/php8.1.load
    state: absent

- name: Entferne defekte php8.1.conf-Symlink
  ansible.builtin.file:
    path: /etc/apache2/mods-enabled/php8.1.conf
    state: absent

- name: Aktiviere Apache-PHP8.2-Modul
  community.general.apache2_module:
    name: php8.2
    state: present
  notify: Reload Apache

- name: Reload Apache for Moodle changes
  ansible.builtin.service:
    name: apache2
    state: reloaded
