---
# roles/moodle/tasks/main.yml

# 1) PHP 8.1 PPA hinzufügen (für Ubuntu-Versionen ohne PHP8.1 im Main-Repo)
- name: Füge Ondřej Surý PHP PPA hinzu
  apt_repository:
    repo: ppa:ondrej/php
    state: present
  become: true

- name: Aktualisiere apt-Cache
  apt:
    update_cache: yes
  become: true

# 2) Installiere PHP 8.1 und benötigte Extensions
- name: Installiere PHP 8.2 und Extensions für Moodle
  apt:
    name:
      - php8.2
      - php8.2-cli
      - libapache2-mod-php8.2
      - php8.2-gd
      - php8.2-curl
      - php8.2-xml
      - php8.2-mbstring
      - php8.2-zip
      - php8.2-intl
      - php8.2-pgsql
    state: present
    update_cache: yes
  become: true

- name: Erstelle Moodle Web-Verzeichnis
  file:
    path: "{{ moodle_www_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: true

- name: Installiere Git
  apt:
    name: git
    state: present
    update_cache: yes
  become: true

- name: Mark Moodle webroot as safe Git directory
  become: true
  command: git config --global --add safe.directory {{ moodle_www_root }}

- name: Klone Moodle Repository
  ansible.builtin.git:
    repo: https://github.com/moodle/moodle.git
    dest: "{{ moodle_www_root }}"
    version: "MOODLE_500_STABLE"
    update: yes
    force: yes
  become: true

- name: Erstelle moodledata-Verzeichnis
  file:
    path: "{{ moodle_data_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0770'
  become: true

- name: Setze Berechtigungen für Moodle Web-Verzeichnis
  file:
    path: "{{ moodle_www_root }}"
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'
  become: true

- name: Deploy Moodle config.php
  template:
    src: config.php.j2
    dest: "{{ moodle_www_root }}/config.php"
    owner: www-data
    group: www-data
    mode: '0644'
  become: true

# 8) Deaktiviere altes PHP-Modul und aktiviere PHP 8.2 im Apache
- name: Entferne defekte php8.1.load-Symlink
  file:
    path: /etc/apache2/mods-enabled/php8.1.load
    state: absent
  become: true

- name: Entferne defekte php8.1.conf-Symlink
  file:
    path: /etc/apache2/mods-enabled/php8.1.conf
    state: absent
  become: true

- name: Aktiviere Apache-PHP8.2-Modul
  community.general.apache2_module:
    name: php8.2
    state: present
  notify: Reload Apache
  become: true

# 9) Reload Apache nach allen Änderungen
- name: Reload Apache for Moodle changes
  service:
    name: apache2
    state: reloaded
  become: true
