---
# roles/postgres/tasks/main.yml
# Diese Rolle installiert und konfiguriert PostgreSQL 14 für Moodle
# und richtet die benötigten Datenbanken und Benutzer ein.

- name: Installiere PostgreSQL 14 Server und Client
  ansible.builtin.apt:
    name:
      - postgresql-14
      - postgresql-client-14
      - postgresql-contrib
    state: present

- name: Installiere Python-PostgreSQL-Adapter
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present

- name: Stelle sicher, dass PostgreSQL läuft
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: PostgreSQL neu starten, damit HBA-Änderungen greifen
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: true

- name: Setze Passwort für postgres-Superuser
  community.postgresql.postgresql_user:
    name: postgres
    password: "{{ postgres_root_password }}"
    role_attr_flags: SUPERUSER
    login_user: postgres
  become: true
  become_user: postgres

- name: Erzeuge Moodle-DB-User
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present
    login_user: postgres
    login_host: 127.0.0.1
    login_password: "{{ postgres_root_password }}"

- name: Erzeuge Moodle-Datenbank
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
    encoding: UTF8
    state: present
    login_user: postgres
    login_host: 127.0.0.1
    login_password: "{{ postgres_root_password }}"
